nodeLinker: node-modules

packageExtensions:
  "eslint-plugin-n@*":
    peerDependencies:
      typescript: "*"
  "@companion-module/tools@*":
    peerDependencies:
      typescript: "*"
enableScripts: false
npmMinimalAgeGate: 3d
npmPreapprovedPackages:
  - "@companion-module/*"
